### ISSUE TITLE
Server Error (500) >> OperationalError at /login/ no such table: leads_user

### ISSUE THREAD

**Issue by sir-meee** [justdjango/getting-started-with-django#14]
I've followed this tutorial to the last until the project is deployed where my issue arises. 
After deploying the project with `DEBUG=FALSE`, I get a Server Error (500) when I login. I then changed the debug setting to true so I can see the error message and it says `OperationalError at /login/` `no such table: leads_user`. I viewed the database schema on my terminal and the table leads_user is present. Running migrations also doesn't solve it.

I finally tried logging in through your deployed project(https://crm.justdjango.com/) and I got a Server Error (500) so I'm assuming this is a problem a lot have faced. 
Anyone know what the fix is?

**Comment by tmbyers1102** [comment]
I have the same issue on the same exact spot. Spent the whole day trying adjustments. Any ideas?

**Comment by sir-meee** [comment]
I deployed to heroku so I fixed this by running migrations on my heroku console `heroku run python manage.py migrate `
