### ISSUE TITLE
Error when updating Lead category

### ISSUE THREAD

**Issue by ZackElias** [justdjango/getting-started-with-django#15]
I have deployed the script successfully but I noticed an issue when trying to update lead category.

Any ideas ?

Error:

Category matching query does not exist.
Request Method:	POST
Request URL:	http://127.0.0.1:8000/leads/1/category/
Django Version:	3.1.4
Exception Type:	DoesNotExist
Exception Value:	
Category matching query does not exist.
Exception Location:	C:\Users\MeCD\AppData\Local\Programs\Python\Python39\lib\site-packages\django\db\models\query.py, line 429, in get
Python Executable:	C:\Users\MeCD\AppData\Local\Programs\Python\Python39\python.exe
Python Version:	3.9.2
Python Path:	
['C:\\getting-started-with-django-main',
 'C:\\Users\\MeCD\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip',
 'C:\\Users\\MeCD\\AppData\\Local\\Programs\\Python\\Python39\\DLLs',
 'C:\\Users\\MeCD\\AppData\\Local\\Programs\\Python\\Python39\\lib',
 'C:\\Users\\MeCD\\AppData\\Local\\Programs\\Python\\Python39',
 'C:\\Users\\MeCD\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages']
Server time:	Tue, 27 Apr 2021 14:00:29 +0000

**Comment by ZackElias** [comment]
I added specific value and now it works

**Comment by Tanujshriyan** [comment]
What specific value?
